468,Fix test that catches AssertionError
2016-11-22T03:41:29Z,discuss,бн from its own call to TestCase.fail.
2016-11-22T03:50:20Z,discuss,This follows up commit cd7477b by cdr@jetbrains.com.
2016-11-25T18:07:49Z,discuss,I've converted test to junit 4 and use @test(expected=AssertionError.class) instead.
2016-11-22T03:37:54Z,commit,Fix test that catches AssertionError,github.com/JetBrains/intellij-community/pull/468/commits/5414416a0c321c245df7ca1468da92aac7f3abdd
